[2024-01-29T01:03:33.042+0100] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: match_id_dag.trigger_match_histories_dag manual__2024-01-29T00:03:02.873469+00:00 [queued]>
[2024-01-29T01:03:33.060+0100] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: match_id_dag.trigger_match_histories_dag manual__2024-01-29T00:03:02.873469+00:00 [queued]>
[2024-01-29T01:03:33.062+0100] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-01-29T01:03:33.090+0100] {taskinstance.py:2192} INFO - Executing <Task(TriggerDagRunOperator): trigger_match_histories_dag> on 2024-01-29 00:03:02.873469+00:00
[2024-01-29T01:03:33.095+0100] {standard_task_runner.py:60} INFO - Started process 18998 to run task
[2024-01-29T01:03:33.100+0100] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'match_id_dag', 'trigger_match_histories_dag', 'manual__2024-01-29T00:03:02.873469+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/match_id_dag.py', '--cfg-path', '/tmp/tmpuwifphwr']
[2024-01-29T01:03:33.104+0100] {standard_task_runner.py:88} INFO - Job 46: Subtask trigger_match_histories_dag
[2024-01-29T01:03:33.151+0100] {task_command.py:423} INFO - Running <TaskInstance: match_id_dag.trigger_match_histories_dag manual__2024-01-29T00:03:02.873469+00:00 [running]> on host ubuntu.ubuntu.virtualbox.org
[2024-01-29T01:03:33.236+0100] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='irachide1@gmail.com' AIRFLOW_CTX_DAG_OWNER='hadoop' AIRFLOW_CTX_DAG_ID='match_id_dag' AIRFLOW_CTX_TASK_ID='trigger_match_histories_dag' AIRFLOW_CTX_EXECUTION_DATE='2024-01-29T00:03:02.873469+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-29T00:03:02.873469+00:00'
[2024-01-29T01:03:33.338+0100] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=match_id_dag, task_id=trigger_match_histories_dag, execution_date=20240129T000302, start_date=20240129T000333, end_date=20240129T000333
[2024-01-29T01:03:33.370+0100] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-29T01:03:33.377+0100] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
