[2024-01-29T00:00:51.643+0100] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: summoner_id_dag.fetch_summoner_ids manual__2024-01-28T23:00:46.406299+00:00 [queued]>
[2024-01-29T00:00:51.651+0100] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: summoner_id_dag.fetch_summoner_ids manual__2024-01-28T23:00:46.406299+00:00 [queued]>
[2024-01-29T00:00:51.651+0100] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-01-29T00:00:51.674+0100] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): fetch_summoner_ids> on 2024-01-28 23:00:46.406299+00:00
[2024-01-29T00:00:51.677+0100] {standard_task_runner.py:60} INFO - Started process 12215 to run task
[2024-01-29T00:00:51.684+0100] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'summoner_id_dag', 'fetch_summoner_ids', 'manual__2024-01-28T23:00:46.406299+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/summoner_id_dag.py', '--cfg-path', '/tmp/tmpgs9_mnw_']
[2024-01-29T00:00:51.687+0100] {standard_task_runner.py:88} INFO - Job 23: Subtask fetch_summoner_ids
[2024-01-29T00:00:51.728+0100] {task_command.py:423} INFO - Running <TaskInstance: summoner_id_dag.fetch_summoner_ids manual__2024-01-28T23:00:46.406299+00:00 [running]> on host ubuntu.ubuntu.virtualbox.org
[2024-01-29T00:00:51.800+0100] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='irachide1@gmail.com' AIRFLOW_CTX_DAG_OWNER='hadoop' AIRFLOW_CTX_DAG_ID='summoner_id_dag' AIRFLOW_CTX_TASK_ID='fetch_summoner_ids' AIRFLOW_CTX_EXECUTION_DATE='2024-01-28T23:00:46.406299+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-28T23:00:46.406299+00:00'
[2024-01-29T00:00:51.802+0100] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-01-29T00:00:51.803+0100] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/hadoop/Desktop/projectBD/scripts/fetch_summoner_ids.py ']
[2024-01-29T00:00:51.814+0100] {subprocess.py:86} INFO - Output:
[2024-01-29T00:00:59.234+0100] {subprocess.py:93} INFO - Successfully uploaded /home/hadoop/Desktop/projectBD/scripts/../summoner_details.json to /user/hadoop/lol/raw
[2024-01-29T00:00:59.250+0100] {subprocess.py:97} INFO - Command exited with return code 0
[2024-01-29T00:00:59.269+0100] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=summoner_id_dag, task_id=fetch_summoner_ids, execution_date=20240128T230046, start_date=20240128T230051, end_date=20240128T230059
[2024-01-29T00:00:59.299+0100] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-29T00:00:59.308+0100] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
